from pathlib import Path

BASE_DIR = Path(__file__).parent

DATA_FILE = BASE_DIR / "data.txt"
MODEL_DIR = BASE_DIR / "my_ai_model"
CHECKPOINT_DIR = BASE_DIR / "checkpoints"
LOG_DIR = BASE_DIR / "logs"

VOCAB_SIZE = 256
BLOCK_SIZE = 128
N_EMBD = 128
N_HEAD = 2
N_LAYER = 2
DROPOUT = 0.2

BATCH_SIZE = 32
EPOCHS = 3
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 0.01
GRAD_CLIP = 1.0
WARMUP_STEPS = 100

EVAL_INTERVAL = 100
EVAL_ITERS = 20
SAVE_INTERVAL = 500

MAX_NEW_TOKENS = 60
TEMPERATURE = 0.8
TOP_K = 40

HOST = "127.0.0.1"
PORT = 8000

SEED = 42
DEVICE = "cuda"